import Head from 'next/head';
import { useQuery } from 'urql';
import { PRODUCT_QUERY } from '../lib/query';

import Service from '../components/Service';
import { Gallery } from '../styles/Gallery';

export default function Home() {
  //Fetch Products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //Check for the data coming in

  if (fetching) return <p>Loading...</p>;
  if (error) return <p>Oh no... {error.message}</p>;
  const services = data.services.data;
  // console.log(services);

  return (
    <div>
      <Head>
        <title>Fitness</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Gallery>
          {services.map((service) => (
            <Service key={service.attributes.Slug} service={service} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
